ERROR:root:'movOpcion'
DEBUG:django.db.backends:(0.000) SELECT "pacifico_aseguradora"."id", "pacifico_aseguradora"."descripcion", "pacifico_aseguradora"."codigo" FROM "pacifico_aseguradora"; args=(); alias=default
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('26327.18'), 'numero_cotizacion': 42, 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.90'), 'calcComiCierreFinal': Decimal('14.12'), 'auxPlazoPago': 92, 'wrkLetraSinSeguros': Decimal('425.33'), 'wrkLetraSeguro': Decimal('20.73'), 'wrkMontoLetra': Decimal('446.06'), 'montoMensualSeguro': Decimal('36.01'), 'wrkLetraConSeguros': Decimal('482.07'), 'tablaTotalPagos': Decimal('41037.52'), 'nombreCliente': 'BANCARIOS', 'valorAuto': Decimal('25000.00'), 'abono': Decimal('2500.00'), 'salarioBaseMensual': Decimal('2000.00'), 'totalDescuentosLegales': Decimal('393.08'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('835.86'), 'salarioNetoActual': Decimal('771.06'), 'salarioNeto': Decimal('288.99'), 'porSalarioNeto': Decimal('14.45'), 'totalIngresosAdicionales': Decimal('500.00'), 'totalIngresosMensualesCompleto': Decimal('2500.00'), 'totalDescuentosLegalesCompleto': Decimal('523.08'), 'salarioNetoActualCompleto': Decimal('1141.06'), 'salarioNetoCompleto': Decimal('658.99'), 'porSalarioNetoCompleto': Decimal('26.36'), 'cosalarioBaseMensual': Decimal('1600.00'), 'cototalDescuentosLegales': Decimal('289.08'), 'cototalDescuentoDirecto': Decimal('0.00'), 'cototalPagoVoluntario': Decimal('120.00'), 'cosalarioNetoActual': Decimal('1190.92'), 'cosalarioNeto': Decimal('708.85'), 'coporSalarioNeto': Decimal('44.30'), 'cototalIngresosAdicionales': Decimal('0.00'), 'cototalIngresosMensualesCompleto': Decimal('1600.00'), 'cototalDescuentosLegalesCompleto': Decimal('289.08'), 'cosalarioNetoActualCompleto': Decimal('1190.92'), 'cosalarioNetoCompleto': Decimal('708.85'), 'coporSalarioNetoCompleto': Decimal('44.30'), 'porcentajeLetraSeguro': Decimal('24.10'), 'coporcentajeLetraSeguro': Decimal('30.13'), 'porcentajeLetraSeguroCompleto': Decimal('19.28'), 'coporcentajeLetraSeguroCompleto': Decimal('30.13'), 'familiarSalarioBaseMensual': Decimal('1961.98'), 'familiarSalarioNeto': Decimal('1479.91'), 'familiarporNetoActual': Decimal('54.50'), 'familiarpoSalarioNeto': Decimal('41.11'), 'familiarNetoActualCompleto': Decimal('2331.98'), 'familiarporNetoActualCompleto': Decimal('145.75'), 'familiarSalarioNetoCompleto': Decimal('1849.91'), 'familiarporSalarioNeto': Decimal('45.12')}
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('26327.18'), 'numero_cotizacion': 42, 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.90'), 'calcComiCierreFinal': Decimal('14.12'), 'auxPlazoPago': 92, 'wrkLetraSinSeguros': Decimal('425.33'), 'wrkLetraSeguro': Decimal('20.73'), 'wrkMontoLetra': Decimal('446.06'), 'montoMensualSeguro': Decimal('36.01'), 'wrkLetraConSeguros': Decimal('482.07'), 'tablaTotalPagos': Decimal('41037.52'), 'nombreCliente': 'BANCARIOS', 'valorAuto': Decimal('25000.00'), 'abono': Decimal('2500.00'), 'salarioBaseMensual': Decimal('2000.00'), 'totalDescuentosLegales': Decimal('393.08'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('835.86'), 'salarioNetoActual': Decimal('771.06'), 'salarioNeto': Decimal('288.99'), 'porSalarioNeto': Decimal('14.45'), 'totalIngresosAdicionales': Decimal('500.00'), 'totalIngresosMensualesCompleto': Decimal('2500.00'), 'totalDescuentosLegalesCompleto': Decimal('523.08'), 'salarioNetoActualCompleto': Decimal('1141.06'), 'salarioNetoCompleto': Decimal('658.99'), 'porSalarioNetoCompleto': Decimal('26.36'), 'cosalarioBaseMensual': Decimal('1600.00'), 'cototalDescuentosLegales': Decimal('289.08'), 'cototalDescuentoDirecto': Decimal('0.00'), 'cototalPagoVoluntario': Decimal('120.00'), 'cosalarioNetoActual': Decimal('1190.92'), 'cosalarioNeto': Decimal('708.85'), 'coporSalarioNeto': Decimal('44.30'), 'cototalIngresosAdicionales': Decimal('0.00'), 'cototalIngresosMensualesCompleto': Decimal('1600.00'), 'cototalDescuentosLegalesCompleto': Decimal('289.08'), 'cosalarioNetoActualCompleto': Decimal('1190.92'), 'cosalarioNetoCompleto': Decimal('708.85'), 'coporSalarioNetoCompleto': Decimal('44.30'), 'porcentajeLetraSeguro': Decimal('24.10'), 'coporcentajeLetraSeguro': Decimal('30.13'), 'porcentajeLetraSeguroCompleto': Decimal('19.28'), 'coporcentajeLetraSeguroCompleto': Decimal('30.13'), 'familiarSalarioBaseMensual': Decimal('1961.98'), 'familiarSalarioNeto': Decimal('1479.91'), 'familiarporNetoActual': Decimal('54.50'), 'familiarpoSalarioNeto': Decimal('41.11'), 'familiarNetoActualCompleto': Decimal('2331.98'), 'familiarporNetoActualCompleto': Decimal('145.75'), 'familiarSalarioNetoCompleto': Decimal('1849.91'), 'familiarporSalarioNeto': Decimal('45.12')}
INFO:django.server:"POST /cotizacion/42/ HTTP/1.1" 200 208740
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py first seen with mtime 1732569332.5018916
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py first seen with mtime 1732569332.5017526
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/formats.py first seen with mtime 1732569332.0692546
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/anaconda3/lib/python3.11/_strptime.py first seen with mtime 1681948558.9095042
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/sessions/serializers.py first seen with mtime 1732569332.5685349
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/__init__.py first seen with mtime 1732569332.0690286
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/session.py first seen with mtime 1732569332.5019946
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/context_processors.py first seen with mtime 1732569332.500866
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/context_processors.py first seen with mtime 1732569332.2745264
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context_processors.py first seen with mtime 1732569332.7133355
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/viewsFideicomiso/cotizadorFideicomiso.py previous mtime: 1736779276.6645827, current mtime: 1736870485.4289355
DEBUG:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/viewsFideicomiso/cotizadorFideicomiso.py notified as changed. Signal results: [(<function template_changed at 0x1074acf40>, None), (<function translation_file_changed at 0x11866dc60>, None)].
INFO:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/viewsFideicomiso/cotizadorFideicomiso.py changed, reloading.
